---
title: "DataWrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) ## install.packages("tidyverse")
```

```{r}
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

gapminder
head(gapminder)
tail(gapminder)
str(gapminder)
summary(gapminder)
library(skimr) # install.packages('skimr')
skim(gapminder)
names(gapminder)
ncol(gapminder)
nrow(gapminder)
c(nrow(gapminder), ncol(gapminder))
skimr::skim(gapminder)
```


```{r}
lowlifeExp <- filter(gapminder,lifeExp<29)
Mexico <- filter(gapminder,country=="Mexico")
filter(gapminder,country %in% c("Mexico","Peru"))
x <- filter(gapminder, country == "Sweden") 
mean(filter(gapminder,country=="Sweden")$lifeExp)
```

```{r}
select(gapminder,year,lifeExp)
select(gapminder,-continent,-lifeExp)
gap_cambodia <- filter(gapminder,country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia,-continent,-lifeExp)
gap_cambodia3 <- select(filter(gapminder,country=="Cambodia"),-continent,-lifeExp)
```

```{r}
# shortcut for pipe operator: ctl+shift+M
gapminder %>% head()
gap_cambodia <- gapminder %>% filter(country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia,-continent,-lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent,-lifeExp)
```


```{r}
gapminder %>% 
  mutate(index=1:nrow(gapminder))

gapminder %>% 
  mutate(planet="earth")

gapminder %>% 
  mutate(GDP=pop*gdpPercap)

gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  #mutate(GDP=pop*gdpPercap) %>% 
    mutate(maxGDP=max(pop*gdpPercap))

gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate(GDP=pop*gdpPercap,maxGDP=max(GDP)) 
```


```{r}
library(tidyverse)
```

```{r}
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap,max_gdp=max(gdp)) %>% 
  ungroup()

gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(max_gdp=max(pop*gdpPercap)) %>% 
  ungroup()

#with summarise
gap_summarise <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  summarise(max_gdp=max(gdp)) %>% 
  ungroup()

gap_grouped 
gap_summarise
```



```{r}
#arrage
gap_summarise <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  summarise(max_gdp=max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp))

gap_summarise
```


```{r}
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

co2 %>% head(10)
co2 %>% tail(10)
co2 %>% dim()

gap_2007 <- gapminder %>% 
  filter(year==2007)

gap_2007 %>% dim()

#join co2 into gapminder

lj <- left_join(gap_2007,co2,by="country")

lj2 <- left_join(co2,gap_2007,by="country")


lj %>% dim()
rj <- right_join(gap_2007,co2)

rj %>% summary()
```




```{r}
# cleaning and changing wide data to long data sets
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')

gap_long <- gap_wide %>% 
  gather(key=obstype_year,value=obs_values,-country,-continent)

gap_wide


gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         -continent, -country) %>%
  separate(obstype_year,
           into = c('obs_type','year'),
           sep = "_",convert=TRUE)


#plot
canada_df <- gap_long %>% 
  filter(country=="Canada",obs_type=="lifeExp")

ggplot(canada_df,aes(x=year,y=obs_values))+
  geom_line()

```

```{r}
life_df <- gap_long %>% 
  filter(obs_type=="lifeExp",continent=="Americas")

ggplot(life_df,aes(x=year,y=obs_values,color=country))+
  geom_line()


mean_life <- gap_long %>% 
  filter(obs_type=="lifeExp",year>1980) %>% 
  group_by(continent,year) %>% 
  summarize(life_ave=mean(obs_values)) %>% 
  ungroup()


mean_life_country <- gap_long %>% 
  filter(obs_type=="lifeExp",year>1980) %>% 
 # group_by(continent,year) %>% 
 # summarize(life_ave=mean(obs_values)) %>% 
#  ungroup()




  ggplot(mean_life,aes(x=year,y=life_ave,color=continent))+
    geom_line()
  

```




```{r}
gap_normal <- gap_long %>% 
  spread(key = obs_type,value = obs_values)

gap_wide

gap_normal

gap_wide2 <- unite(gap_long,type_year,sep="_",-continent,-country,-obs_values,remove=TRUE) %>% 
  spread(key=type_year,value = obs_values)

#Alternatively
gap_wide3 <- unite(gap_long,type_year,obs_type,sep="_",year,remove=TRUE) %>% 
  spread(key=type_year,value = obs_values)



```







